# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_threshold <- function(z, lambda) {
    .Call('_CdaPrac1_soft_threshold', PACKAGE = 'CdaPrac1', z, lambda)
}

lasso_cda_cpp <- function(X, y, lambda, max_iter = 1000L, tol = 1e-6) {
    .Call('_CdaPrac1_lasso_cda_cpp', PACKAGE = 'CdaPrac1', X, y, lambda, max_iter, tol)
}

